#pragma once
#include <algorithm>
#include <conio.h> 
#include <fstream>
#include <time.h>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
#include "Player.h"
#include "Ranking.h"
#include "EvtActEnd.h"
#include "UI.h"
#include "GameManager.h"